hn_crawling_experiment/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

hn_crawling_experiment/hn_crawling_experiment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('common/', include('common.urls')),
    path('api/', include('rest_framework.urls')),
]

hn_crawling_experiment/main/urls.py
from django.urls import include, path

from .views import PostViewSet, UserViewSet, DataViewSet

from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers



router = routers.SimpleRouter()
router.register('post', PostViewSet, basename='post')
router.register('user', UserViewSet, basename='user')
router.register('data', DataViewSet, basename='data')

urlpatterns = [
    path('', include(router.urls))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hn_crawling_experiment/common/models.py
from django.db import models

# Create your models here.

hn_crawling_experiment/main/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    weeks = models.CharField(max_length=30) # "3월 2주차"
    index = models.IntegerField() # 0 ~ 3
    news = models.TextField() # {"date": "2025-05-24", "postname": "Hello world Title", "contents": "Hello world Content"}
    image = models.TextField() # '7JWI64WVpw=='

    # postname = models.CharField(max_length=50)
    # mainphoto = models.ImageField(blank=True, null=True)
    # contents = models.TextField()

    def __str__(self):
        return self.weeks

class User(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=30)
    categories = models.CharField(max_length=10, default="000") # back-front-ai, 000 ~ 111

hn_crawling_experiment/common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout

# Create your views here.

def logout_view(request):
    logout(request)
    return redirect('index')

hn_crawling_experiment/main/views.py
from .models import Post, User

from .serializers import PostSerializer, UserSerializer

from rest_framework import viewsets, mixins
from rest_framework.response import Response
from rest_framework import status



# Create your views here.

class PostViewSet(mixins.ListModelMixin, viewsets.GenericViewSet):
    serializer_class = PostSerializer

    def get_queryset(self):
        queryset = Post.objects.filter(index=0) # 기본적으로는 index가 0인 애들(메인페이지용)
        
        weeks = self.request.query_params.get('weeks', None) # weeks가 인자로 들어왔으면 값, 안 들어왔으면 None
        
        if weeks is not None: # 인자 들어옴(/post?weeks='2025-5-4')
            queryset = Post.objects.filter(weeks=weeks) # weeks가 '2025-5-4'인 애들

        return queryset
    

class UserViewSet(mixins.CreateModelMixin, mixins.ListModelMixin, viewsets.GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()

    def create(self, request):
        category_arr = request.data['categories']
        
        category_dict = {'web': '0', 'ai': '0', 'game': '0'}
        
        for category in category_arr:
            category_dict[category] = '1'
        
        req = ""
        for val in category_dict.values():
            req += val
        mod_request = request
        mod_request.data['categories'] = req

        serializer = UserSerializer(data=mod_request.data)
        # serializer = UserSerializer(data=request.data)
        
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def list(self, request, *args, **kwargs):
        ALLOWED_GET_IP = [
            '127.0.0.1',
            '172.23.0.1',
        ]

        ip_addr = request.META['REMOTE_ADDR']

        if ip_addr not in ALLOWED_GET_IP:
            return Response(status=status.HTTP_400_BAD_REQUEST)
        
        queryset = self.get_queryset()

        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

class DataViewSet(mixins.CreateModelMixin, viewsets.GenericViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    
    def create(self, request):
        ALLOWED_POST_IP = [
            '127.0.0.1',
            '172.23.0.1',
        ]

        ip_addr = request.META['REMOTE_ADDR']

        if ip_addr not in ALLOWED_POST_IP:
            return Response(status=status.HTTP_400_BAD_REQUEST)

        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

hn_crawling_experiment/main/templates/main/index.html
{% extends 'base.html' %}
{% block content %}
	<h1>Newsis Website!</h1>
	<button><a href="new_post/">글쓰기</a></button>
	<table>
	{% for list in postlist %}
		<ul>
			<li><a href="{{list.pk}}/">{{list.postname}}</a></li>
		</ul>
	{% endfor %}
	</table>

	<ul>
		{% if postlist.has_previous %}
		<li>
			<a href="?page={{ postlist.previous_page_number }}">이전</a>
		</li>
		{% else %}
		<li>
			<a tabindex="-1" aria-disabled="true" href="#">이전</a>
		</li>
		{% endif %}

		{% for page_number in postlist.paginator.page_range %}
		{% if page_number == postlist.number %}
		<li aria-current="page">
			<a href="?page={{ page_number }}">{{ page_number }}</a>
		</li>
		{% else %}
		<li>
			<a href="?page={{ page_number }}">{{ page_number }}</a>
		</li>
		{% endif %}
		{% endfor %}

		{% if postlist.has_next %}
		<li>
			<a href="?page={{ postlist.next_page_number }}">다음</a>
		</li>
		{% else %}
		<li>
			<a tabindex="-1" aria-disabled="true" href="#">다음</a>
		</li>
		{% endif %}
	</ul>
{% endblock %}

hn_crawling_experiment/main/templates/main/new_post.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>글쓰기 페이지</title>
</head>
<body>
	<h1>글쓰기 페이지</h1>
	<form method="POST"  enctype="multipart/form-data">
		{% csrf_token %} <!-- enhance security -->
		제목<br>
		<input type="text" name="postname"><br>
		내용<br>
		<textarea rows="10" cols="50" name="contents"></textarea><br>
		<input type="file" name="mainphoto"><br>
		<input type="submit" value="글쓰기">
	</form>
</body>
</html>

hn_crawling_experiment/main/templates/main/posting.html
<html>
	<head>
		<title>Posting</title>
	</head>
	<body>
		<p>{{post.postname}}</p>
		<p>{{post.contents}}</p>
		{% if post.mainphoto %}
			<img src = "{{ post.mainphoto.url }}" alt="" height="600">
			<br>
		{% endif %}
		<a href="/">list</a>
	</body>
</html>

hn_crawling_experiment/templates/base.html
<!doctype html>
<html lang="ko">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Newsis Website!</title>
</head>
<body>
	{% include "navbar.html" %}
	
	{% block content %}
	{% endblock content %}
</body>
</html>

hn_crawling_experiment/templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div>
	<form method="post" action="{% url 'common:login' %}">
		{%csrf_token %}
		{% include "form_errors.html" %}
		<div>
			<label for="username">사용자ID</label>
			<input type="text" name="username" id="username"
							   value="{{ form.username.value|default_if_none:'' }}">
		</div>
		<div>
			<label for="password">비밀번호</label>
			<input type="password" name="password" id="password"
							       value="{{ form.password.value|default_if_none:'' }}">
		</div>
		<button type="submit">로그인</button>
	</form>
</div>
{% endblock %}

hn_crawling_experiment/templates/form_errors.html
{% if form.erros %}
<div class="alert alert-danger">
	{% for field in form %}
	{% if field.errors %}
	<div>
		<strong>{{ field.label }}</strong>
		{{ field.errors }}
	</div>
	{% endif %}
	{% endfor %}
	
	{% for error in form.non_field_errors %}
	<div>
		<strong>{{ error }}</strong>
	</div>
	{% endfor %}
</div>
{% endif %}

hn_crawling_experiment/templates/navbar.html
<nav>
	<ul class="navbar-nav" style="list-style-type: none;">
		<li style="padding: 80px; float: left;"></li>
		<li style="padding: 80px; float: left;">Newsis Website</li>
		<li class="nav-item" style="padding: 80px; float: left;">
			{% if user.is_authenticated %}
			<a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
			{% else %}
			<a class="nav-link" href="{% url 'common:login' %}">로그인</a>
			{% endif %}
		</li>
	</ul>
</nav>